name: Build on Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Only trigger on tags like v1.2.3

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Tuist
        uses: jdx/mise-action@v2

      - name: Download opencv2.xcframework
        run: |
          mkdir -p vendor/frameworks
          curl -L -o vendor/frameworks/opencv2.xcframework.zip https://github.com/MaximKalinin/MartyDetector/releases/download/opencv-86a963cec9/opencv2.xcframework.zip
          unzip vendor/frameworks/opencv2.xcframework.zip -d vendor/frameworks

      - name: Generate Xcode project
        run: tuist generate

      - name: Build project
        run: |
          xcodebuild \
            -scheme MartyDetector \
            -configuration Release \
            -derivedDataPath build

      - name: Zip .app bundle
        run: |
          cd build/Build/Products/Release
          zip -r MartyDetector.app.zip MartyDetector.app

      - name: Upload zipped .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: MartyDetector-App
          path: build/Build/Products/Release/MartyDetector.app.zip
